/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DentalGest;

import java.awt.HeadlessException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Paolo
 */
public final class AddCliente extends javax.swing.JFrame {

    

    Connection conn = null;
    Connection connCheck = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    PreparedStatement pstcheck = null;
    ResultSet rscheck = null;
    /**
     * Creates new form adesione_servizi
     */

    
     private static AddCliente obj=null;
    
    public static AddCliente getObj(){
        if(obj==null){
            obj=new AddCliente();
        }return obj;
    }

    
      

    private AddCliente() {
        initComponents();
        conn = Db.db();
        connCheck = Db.db();
        AnimationStation();
    }

     
    private void AnimationStation() {
        MouseAdapter ma = new MouseAdapter() {
            int lastX, lastY;

            @Override
            public void mousePressed(MouseEvent e) {
                lastX = e.getXOnScreen();
                lastY = e.getYOnScreen();
            }

            @Override
            public void mouseDragged(MouseEvent e) {
                int x = e.getXOnScreen();
                int y = e.getYOnScreen();
                // Move frame by the mouse delta
                setLocation(getLocationOnScreen().x + x - lastX,
                        getLocationOnScreen().y + y - lastY);
                lastX = x;
                lastY = y;
            }
        };
        addMouseListener(ma);
        addMouseMotionListener(ma);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lab_pec = new javax.swing.JLabel();
        lab_mail = new javax.swing.JLabel();
        lab_codfisc = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_cognome = new javax.swing.JTextField();
        txt_recapito = new javax.swing.JTextField();
        txt_codfisc = new javax.swing.JTextField();
        lab_formagiur = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("dentalsoft");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(null);

        lab_pec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_pec.setText("Cognome:");
        getContentPane().add(lab_pec);
        lab_pec.setBounds(340, 80, 70, 17);

        lab_mail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_mail.setText("Nome:");
        getContentPane().add(lab_mail);
        lab_mail.setBounds(40, 80, 50, 17);

        lab_codfisc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_codfisc.setText("Codice Fiscale:");
        getContentPane().add(lab_codfisc);
        lab_codfisc.setBounds(40, 120, 100, 17);

        txt_nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        getContentPane().add(txt_nome);
        txt_nome.setBounds(110, 80, 180, 19);

        txt_cognome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_cognome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        getContentPane().add(txt_cognome);
        txt_cognome.setBounds(420, 80, 220, 20);

        txt_recapito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_recapito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        getContentPane().add(txt_recapito);
        txt_recapito.setBounds(440, 120, 200, 19);

        txt_codfisc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_codfisc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        getContentPane().add(txt_codfisc);
        txt_codfisc.setBounds(140, 120, 190, 19);

        lab_formagiur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_formagiur.setText("Recapito:");
        getContentPane().add(lab_formagiur);
        lab_formagiur.setBounds(370, 120, 70, 17);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalgest/images/pulsanti/chiudi.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(690, 10, 20, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DentalGest/images/minimizza.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(670, 10, 20, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalgest/images/pulsanti/aggiungi.png"))); // NOI18N
        jButton1.setAlignmentX(0.5F);
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 170, 70, 25);

        setSize(new java.awt.Dimension(710, 216));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        ClientiList.getObj().setVisible(true);
        ClientiList.getObj().setExtendedState(JFrame.NORMAL);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ClientiList cl = new ClientiList();
        String query_check = "select * from pazienti where codice_fiscale=?";
        String val1 = txt_nome.getText().toLowerCase();
        String val2 = txt_cognome.getText().toLowerCase();
        String val3 = txt_codfisc.getText().toLowerCase();
        String val4 = txt_recapito.getText().toLowerCase();
        int x = JOptionPane.showConfirmDialog(null, "Sei sicuro di voler aggiugere il seguente paziente?", "Aggiungi Paziente", JOptionPane.YES_NO_OPTION);
        if (x == 0) {
            try {
                System.out.println("Arrivo 1");
                pstcheck = connCheck.prepareStatement(query_check);
                pstcheck.setString(1, val3);
                rscheck = pstcheck.executeQuery();
                if (rscheck.next()) {
                    JOptionPane.showMessageDialog(null, "Paziente già esistente");
                } else {
                    System.out.println("Arrivo 2");
                    String sql = "insert into pazienti (nome,cognome,codice_fiscale,cell) values (?,?,?,?)";
                    pst = conn.prepareStatement(sql);
                    System.out.println("Query: "+sql);
                    pst.setString(1, val1);
                    pst.setString(2, val2);
                    pst.setString(3, val3);
                    pst.setString(4, val4);
                    System.out.println("VALORI INSERIMENT PAZIENTE: " + val1 + " | " + val2 + " | " + val3 + " | " + val4 + " ");
                    System.out.println("Arrivo 3");
                   
                        pst.execute();
                        System.out.println("VALORI INSERIMENT PAZIENTE: " + val1 + " | " + val2 + " | " + val3 + " | " + val4 + " ");
 System.out.println("Arrivo 4");
                        JOptionPane.showMessageDialog(null, "paziente aggiunto correttamente");

                    

                }
 System.out.println("Arrivo 5");
                txt_cognome.setText("");
                txt_codfisc.setText("");
                
                txt_nome.setText("");
                txt_recapito.setText("");
                cl.PopulateData();
                dispose();
                cl.setVisible(true);
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Errore aggiunta record");
            } finally {
                try {
                    rscheck.close();
                    pst.close();
                } catch (SQLException e) {

                }
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddCliente().setVisible(true);
            
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lab_codfisc;
    private javax.swing.JLabel lab_formagiur;
    private javax.swing.JLabel lab_mail;
    private javax.swing.JLabel lab_pec;
    private javax.swing.JTextField txt_codfisc;
    private javax.swing.JTextField txt_cognome;
    public javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_recapito;
    // End of variables declaration//GEN-END:variables
}
