/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DentalGest;

import java.awt.HeadlessException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Paolo
 */
public final  class ClientiList extends javax.swing.JFrame {
  
    String msg1 = null;
     String msg3 = null;
    String msg2 = null;
    Connection conn=null;
    Connection connUpd=null;
    Connection connDel=null;
    Connection connDelCli=null;
    Connection connDelPrest=null;
    Connection connDelApp=null;
    Connection connSearch=null;
    Connection connRef=null;
    Connection connClick = null;
    Connection connCheck = null;
    Connection connPop = null;
    Connection connIns = null;
    Connection connUpdStato = null;
    ResultSet rsUpd=null;
    ResultSet rsDel=null;
    ResultSet rsSearch=null;
    ResultSet rs = null;
    Statement pstd=null;
    PreparedStatement pst=null;
    PreparedStatement pstUpd=null;
    PreparedStatement psclick = null;
        Statement pstDel=null;
        Statement pstDelCli=null;
        Statement pstDelApp=null;
        Statement pstDelPrest=null;
        PreparedStatement pstPop = null;
    PreparedStatement pstSearch=null;
    PreparedStatement pstcheck=null;
    PreparedStatement pstIns = null;
     ResultSet rsclick = null;
     ResultSet rsd = null;
     ResultSet rsPop = null;
     ResultSet rscheck = null;
    /**
     * Creates new form Clients
     */
    ClientiList() {
        initComponents();
          
        conn=Db.db();
         connDel= Db.db();
         connUpd=Db.db();
         connSearch= Db.db();
         connRef = Db.db();
         connClick = Db.db();
         connIns = Db.db();
         connCheck = Db.db();
         connDelApp = Db.db();
         connDelPrest = Db.db();
         connDelCli = Db.db();
         connUpdStato = Db.db();
    PopulateData();
    AnimationStation();
            
       
    }
    
//    public static boolean isMyResultSetEmpty(ResultSet rs) throws SQLException {
//         return (!rs.isBeforeFirst() && rs.getRow() == 0);
//    }
    
    public void AnimationStation() {
    MouseAdapter ma = new MouseAdapter() {
        int lastX, lastY;
   
        @Override
        public void mousePressed(MouseEvent e) {
            lastX = e.getXOnScreen();
            lastY = e.getYOnScreen();
        }
        
        @Override
        public void mouseDragged(MouseEvent e) {
            int x = e.getXOnScreen();
            int y = e.getYOnScreen();
            // Move frame by the mouse delta
            setLocation(getLocationOnScreen().x + x - lastX,
                    getLocationOnScreen().y + y - lastY);
            lastX = x;
            lastY = y;
        }
    };
    addMouseListener(ma);
    addMouseMotionListener(ma);
}
    private static ClientiList obj=null;
    
    public static ClientiList getObj(){
        if(obj==null){
            obj=new ClientiList();
        }return obj;
    }
        
    void Refresh() {
       
        int i = 0;
         int j=0; 
        String sql = "SELECT * FROM  pazienti ORDER BY nome ASC";
               

       try{
            pstd = connRef.createStatement();
            rsd = pstd.executeQuery(sql);
            tb1.setModel(DbUtils.resultSetToTableModel(rsd));
           
            i =tb1.getRowCount();
          
            System.out.println("Numero righe tabella prestazioni: "+(i));
            
            if(i==0){
                JOptionPane.showMessageDialog(null, "Nessuna prestazione disponibile");
            }
            
       }
          catch(HeadlessException | SQLException e){
           JOptionPane.showMessageDialog(null, "Errore caricamento prestazioni");

                  }
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDateChooserBeanInfo1 = new com.toedter.calendar.JDateChooserBeanInfo();
        bnt_agg_sek = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        bt_cerca = new javax.swing.JButton();
        txt_cerca = new javax.swing.JTextField();
        bt_elim2 = new javax.swing.JButton();
        bnt_mod = new javax.swing.JButton();
        lab_mail = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        lab_pec = new javax.swing.JLabel();
        txt_cognome = new javax.swing.JTextField();
        lab_codfisc = new javax.swing.JLabel();
        txt_codfisc = new javax.swing.JTextField();
        lab_formagiur = new javax.swing.JLabel();
        txt_recapito = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txt_nominativo = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        cogn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtdataN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        labTag = new javax.swing.JLabel();
        combo_stato = new javax.swing.JComboBox<>();
        texTag = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DentalGest");
        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        bnt_agg_sek.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bnt_agg_sek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DentalGest/images/pulsanti/aggiungi_150x40.png"))); // NOI18N
        bnt_agg_sek.setAlignmentY(2.0F);
        bnt_agg_sek.setBorder(null);
        bnt_agg_sek.setBorderPainted(false);
        bnt_agg_sek.setContentAreaFilled(false);
        bnt_agg_sek.setFocusPainted(false);
        bnt_agg_sek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_agg_sekActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 230;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -40;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 5, 0, 0);
        getContentPane().add(bnt_agg_sek, gridBagConstraints);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tb1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tb1.setAutoscrolls(false);
        tb1.setFocusable(false);
        tb1.getTableHeader().setReorderingAllowed(false);
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 244;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 797;
        gridBagConstraints.ipady = 190;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 10, 0, 12);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        bt_cerca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_cerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DentalGest/images/pulsanti/icona_lente_ingrandimento_cerca_40x40.png"))); // NOI18N
        bt_cerca.setAlignmentY(0.0F);
        bt_cerca.setBorder(null);
        bt_cerca.setBorderPainted(false);
        bt_cerca.setContentAreaFilled(false);
        bt_cerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cercaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 29;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 102, 0, 0);
        getContentPane().add(bt_cerca, gridBagConstraints);

        txt_cerca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_cerca.setMinimumSize(new java.awt.Dimension(86, 28));
        txt_cerca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_cercaMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 10, 0, 0);
        getContentPane().add(txt_cerca, gridBagConstraints);

        bt_elim2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_elim2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DentalGest/images/pulsanti/elimina_150x40.png"))); // NOI18N
        bt_elim2.setBorder(null);
        bt_elim2.setBorderPainted(false);
        bt_elim2.setContentAreaFilled(false);
        bt_elim2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_elim2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 197;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -60;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 10, 0, 0);
        getContentPane().add(bt_elim2, gridBagConstraints);

        bnt_mod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bnt_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DentalGest/images/pulsanti/modifica_150x40.png"))); // NOI18N
        bnt_mod.setAlignmentY(2.0F);
        bnt_mod.setBorder(null);
        bnt_mod.setBorderPainted(false);
        bnt_mod.setContentAreaFilled(false);
        bnt_mod.setFocusPainted(false);
        bnt_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_modActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 73;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 63;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -50;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 2, 0, 0);
        getContentPane().add(bnt_mod, gridBagConstraints);

        lab_mail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_mail.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 43;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        getContentPane().add(lab_mail, gridBagConstraints);

        txt_nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 104;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 94;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 9, 0, 0);
        getContentPane().add(txt_nome, gridBagConstraints);

        lab_pec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_pec.setText("Cognome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        getContentPane().add(lab_pec, gridBagConstraints);

        txt_cognome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_cognome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_cognome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cognomeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        getContentPane().add(txt_cognome, gridBagConstraints);

        lab_codfisc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_codfisc.setText("Codice Fiscale:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        getContentPane().add(lab_codfisc, gridBagConstraints);

        txt_codfisc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_codfisc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
        getContentPane().add(txt_codfisc, gridBagConstraints);

        lab_formagiur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_formagiur.setText("Recapito:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 73;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 2, 0, 0);
        getContentPane().add(lab_formagiur, gridBagConstraints);

        txt_recapito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_recapito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 135;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 95;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
        getContentPane().add(txt_recapito, gridBagConstraints);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DentalGest/images/pulsanti/apri-scheda-cliente_150x40.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 232;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -20;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 10, 0, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        txt_nominativo.setEditable(false);
        txt_nominativo.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(txt_nominativo, gridBagConstraints);

        nom.setEditable(false);
        nom.setBorder(null);
        nom.setEnabled(false);
        nom.setFocusable(false);
        nom.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(nom, gridBagConstraints);

        cogn.setEditable(false);
        cogn.setBorder(null);
        cogn.setEnabled(false);
        cogn.setFocusable(false);
        cogn.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(cogn, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Data di Nascita: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 230;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        txtdataN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtdataN.setMinimumSize(new java.awt.Dimension(2, 19));
        txtdataN.setPreferredSize(new java.awt.Dimension(2, 19));
        txtdataN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdataNActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 232;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 68;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        getContentPane().add(txtdataN, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DentalGest/images/headers/ANAGRAFICA_PAZIENTE_220_x_80.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(295, 80));
        jLabel1.setMinimumSize(new java.awt.Dimension(295, 80));
        jLabel1.setPreferredSize(new java.awt.Dimension(295, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = -77;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jButton6.setText("Modifica stato");
        jButton6.setToolTipText("");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 230;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 20, 0, 0);
        getContentPane().add(jButton6, gridBagConstraints);

        id.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        id.setBorder(null);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 30;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(id, gridBagConstraints);

        labTag.setText("Tag:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 10, 26, 0);
        getContentPane().add(labTag, gridBagConstraints);

        combo_stato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In corso", "Terminato", "Pagato" }));
        combo_stato.setSelectedIndex(-1);
        combo_stato.setToolTipText("");
        combo_stato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 235;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 1, 0, 0);
        getContentPane().add(combo_stato, gridBagConstraints);

        texTag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        texTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texTagActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 12, 26, 0);
        getContentPane().add(texTag, gridBagConstraints);

        setSize(new java.awt.Dimension(856, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
       
            try {
            final int row = this.tb1.getSelectedRow();
            final String tbclick = this.tb1.getModel().getValueAt(row, 3).toString();
            final String tbclick2 = this.tb1.getModel().getValueAt(row, 2).toString();
            final String tbclick3 = this.tb1.getModel().getValueAt(row, 4).toString();
            final String sql = "SELECT * FROM pazienti WHERE nome = ? and cognome = ? and datanascita =?";
            (this.psclick = this.connClick.prepareStatement(sql)).setString(1, tbclick);
            this.psclick.setString(2, tbclick2);
            this.psclick.setString(3, tbclick3);
            this.rsclick = this.psclick.executeQuery();
            if (this.rsclick.next()) {
                final String addT = this.rsclick.getString("tag");
                this.texTag.setText(addT);
                final String add1 = this.rsclick.getString("nome");
                this.txt_nome.setText(add1);
                this.nom.setText(add1);
                final String add2 = this.rsclick.getString("cognome");
                this.txt_cognome.setText(add2);
                this.cogn.setText(add2);
                final String add3 = this.rsclick.getString("codice_fiscale");
                this.txt_codfisc.setText(add3);
                final String add4 = this.rsclick.getString("cell");
                this.txt_recapito.setText(add4);
                final String add5 = this.rsclick.getString("datanascita");
                this.txtdataN.setText(add5);
                final String add6 = this.rsclick.getString("id");
                this.id.setText(add6);
                this.combo_stato.setSelectedItem(this.rsclick.getString("stato"));
                this.msg1 = this.txt_nome.getText();
                this.msg2 = this.txt_cognome.getText();
                this.msg3 = this.id.getText();
                System.out.println("Nome da passare: " + this.msg1);
                System.out.println("Cognome da passare: " + this.msg2);
                System.out.println("cf da passare: " + this.msg3);
            }
        }
        catch (SQLException e) {
            e.getMessage();
        }
        
            
            
            
    }//GEN-LAST:event_tb1MouseClicked

    private void bt_cercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cercaActionPerformed
        // TODO add your handling code here:
        Search();
    }//GEN-LAST:event_bt_cercaActionPerformed

    private void bnt_agg_sekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_agg_sekActionPerformed
        // TODO add your handling code here:
        
         final int leftLimit = 97;
        final int rightLimit = 122;
        final int targetStringLength = 10;
        final Random random = new Random();
        final String generatedString = random.ints(leftLimit, rightLimit + 1).limit(targetStringLength).collect(StringBuilder::new, StringBuilder::appendCodePoint, StringBuilder::append).toString();
        System.out.println("id utente: " + generatedString);
        final String query_check = "select * from pazienti where codice_fiscale=?";
        final String val0 = this.texTag.getText();
        final String val2 = this.txt_nome.getText();
        final String val3 = this.txt_cognome.getText();
        final String val4 = this.txt_codfisc.getText();
        final String val5 = this.txt_recapito.getText();
        final String val6 = this.txtdataN.getText();
        final String val7 = "In corso";
        final int x = JOptionPane.showConfirmDialog(null, "Sei sicuro di voler aggiugere il seguente paziente?", "Aggiungi Paziente", 0);
        if (x == 0) {
            try {
                System.out.println("Arrivo 1");
                (this.pstcheck = this.connCheck.prepareStatement(query_check)).setString(1, val4);
                this.rscheck = this.pstcheck.executeQuery();
                if (this.rscheck.next()) {
                    JOptionPane.showMessageDialog(null, "Paziente gi\u00e0 esistente");
                }
                else {
                    System.out.println("Arrivo 2");
                    final String sql = "insert into pazienti (nome,cognome,codice_fiscale,cell,datanascita,stato,id,tag) values (?,?,?,?,?,?,?,?)";
                    this.pstIns = this.connIns.prepareStatement(sql);
                    System.out.println("Query: " + sql);
                    this.pstIns.setString(1, val2);
                    this.pstIns.setString(2, val3);
                    this.pstIns.setString(3, val4);
                    this.pstIns.setString(4, val5);
                    this.pstIns.setString(5, val6);
                    this.pstIns.setString(6, val7);
                    this.pstIns.setString(7, generatedString);
                    this.pstIns.setString(8, val0);
                    System.out.println("VALORI INSERIMENT PAZIENTE: " + val0 + " | " + val2 + " | " + val3 + " | " + val4 + " | " + val5 + " | " + val6 + " " + val7 + " " + generatedString);
                    JOptionPane.showMessageDialog(null, "paziente aggiunto correttamente");
                }
                this.pstIns.execute();
                this.txt_cognome.setText("");
                this.txt_codfisc.setText("");
                this.txt_nome.setText("");
                this.txt_recapito.setText("");
                this.txtdataN.setText("");
                this.texTag.setText("");
                this.PopulateData();
            }
            catch (SQLException | HeadlessException ex2) {
                
                JOptionPane.showMessageDialog(null, "Errore aggiunta record");
            }
        }
        
    }//GEN-LAST:event_bnt_agg_sekActionPerformed

    private void bt_elim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_elim2ActionPerformed
        // TODO add your handling code here:
        final Object[] options = { "Si", "No" };
        String strNome = null;
        String strCognome = null;
        String cliente = null;
        String nascita = null;
        String id = null;
        final int n = JOptionPane.showOptionDialog(null, "Sei sicuro di voler cancellare i pazienti selezionati?", "Conferma cancellazione?", 1, 3, null, options, options[1]);
        if (n == 0) {
            for (int i = 0; i < this.tb1.getRowCount(); ++i) {
                final Boolean chkDel = Boolean.valueOf(this.tb1.getValueAt(i, 0).toString());
                if (chkDel) {
                    strNome = this.tb1.getValueAt(i, 3).toString();
                    strCognome = this.tb1.getValueAt(i, 2).toString();
                    nascita = this.tb1.getValueAt(i, 4).toString();
                    cliente = strNome + " " + strCognome;
                    id = this.tb1.getValueAt(i, 7).toString();
                    System.out.println("Il cliente che viene terminato " + cliente);
                    this.DeleteData(strNome, strCognome, nascita, id);
                    this.DeleteDataRich(cliente, nascita);
                    this.DeleteDataPrest(cliente, id);
                    this.DeleteDataCart(cliente, id);
                }
            }
            JOptionPane.showMessageDialog(null, "Paziente/i cancallati correttamente");
            this.txt_cognome.setText("");
            this.txt_codfisc.setText("");
            this.txt_recapito.setText("");
            this.txt_nome.setText("");
            this.txtdataN.setText("");
            this.texTag.setText("");
            this.PopulateData();
            AppList.getObj().PopulateData();
        }
        this.PopulateData();
                        //AppList.getObj().PopulateDataAll();
        


    }//GEN-LAST:event_bt_elim2ActionPerformed

    private void bnt_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_modActionPerformed
        // TODO add your handling code here:
        final int x = JOptionPane.showConfirmDialog(null, "Sei sicuro di voler aggiornare l'anagrafica del seguente paziente?", "Aggiorna Anagrafica Paziente", 0);
        if (x == 0) {
            try {
                final String val0 = this.texTag.getText();
                final String val2 = this.txt_nome.getText();
                final String val3 = this.txt_cognome.getText();
                final String val4 = this.txt_codfisc.getText();
                final String val5 = this.txt_recapito.getText();
                final String val6 = this.nom.getText();
                final String val7 = this.cogn.getText();
                final String val8 = this.txtdataN.getText();
                final String val9 = this.id.getText();
                final String sql = "update pazienti set nome=?,cognome=?,codice_fiscale=?,cell=?,datanascita=?,tag =? where nome=? and cognome=? and id=?";
                (this.pstUpd = this.connUpd.prepareStatement(sql)).setString(1, val2);
                this.pstUpd.setString(2, val3);
                this.pstUpd.setString(3, val4);
                this.pstUpd.setString(4, val5);
                this.pstUpd.setString(5, val8);
                this.pstUpd.setString(6, val0);
                this.pstUpd.setString(7, val6);
                this.pstUpd.setString(8, val7);
                this.pstUpd.setString(9, val9);
                this.pstUpd.execute();
                JOptionPane.showMessageDialog(null, "Anagrafica paziente " + val2 + " " + val3 + " modificata correttamente");
                this.txt_nome.setText("");
                this.txt_cognome.setText("");
                this.txt_codfisc.setText("");
                this.txt_recapito.setText("");
                this.txtdataN.setText("");
                this.id.setText("");
                this.texTag.setText("");
                this.PopulateData();
            }
            catch (SQLException | HeadlessException ex2) {
                
                JOptionPane.showMessageDialog(null, "Errore modifica anagrafica paziente");
            }
        }
        this.PopulateData();
        
    }//GEN-LAST:event_bnt_modActionPerformed

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeActionPerformed

    private void txt_cognomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cognomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cognomeActionPerformed

    private void txt_cercaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_cercaMouseClicked
        // TODO add your handling code here:
        if(txt_cerca.getText().equals(""))
        {
            PopulateData();
        }
    }//GEN-LAST:event_txt_cercaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      String msg = txt_nominativo.getText();
      
      if(nom.getText().equals("") && cogn.getText().equals(""))
      {
          JOptionPane.showMessageDialog(null, "Selezionare paziente");
      }
      else
      {
          Clients.getObj().txt_n.setText(msg1);
      Clients.getObj().txt_c.setText(msg2);
      Clients.getObj().txt_d.setText(msg3);
      System.out.println("passaggio nome: "+msg1);
      System.out.println("passaggio cognome: "+msg2);
       System.out.println("passaggio data nascita: "+msg3);
      Clients.getObj().Update_table();
      Clients.getObj().PopulatePrest();
      Clients.getObj().setVisible(true);
      }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtdataNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdataNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdataNActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

       
        try{

            String stato = combo_stato.getSelectedItem().toString();
            if(stato.isEmpty()){JOptionPane.showMessageDialog(null, "Nessuno Stato selezionato");}
            else{
                int x = JOptionPane.showConfirmDialog(null,"Sei sicuro di voler aggiornare il seguente stato?","Aggiorna Stato",JOptionPane.YES_NO_OPTION);
                if(x==0){
                    int row = tb1.getSelectedRow();

                    String nome = tb1.getValueAt(row, 2).toString();
                    String cognome = tb1.getValueAt(row, 1).toString();
                    String datanascita = tb1.getValueAt(row, 3).toString();
                    String id = tb1.getValueAt(row, 6).toString();
                    System.out.println("nome "+nome+" "+cognome);
                    System.out.println("datanascita "+datanascita);
                    System.out.println("stato "+stato);
                    System.out.print("qui arrivo");
                    String sql="update pazienti set stato='"+stato+"' where id = '"+id+"'";
                    PreparedStatement pstUpdStato = connUpdStato.prepareStatement(sql);
                    pstUpdStato.execute();
                    System.out.print("anche qui arrivo");
                    //tb1.removeColumn(tb1.getColumnModel().getColumn(1));
                    //tb1.removeColumn(tb1.getColumnModel().getColumn(5));

                    //tb1.removeColumn(tb1.getColumnModel().getColumn(5));

                    JOptionPane.showMessageDialog(null,"Stato modificato correttamente per "+nome+" "+cognome);
                    PopulateData();
                    txt_cognome.setText("");
                txt_codfisc.setText("");
                
                txt_nome.setText("");
                txt_recapito.setText("");
                txtdataN.setText("");
                combo_stato.setSelectedIndex(-1);
                

                    //AppList.getObj().PopulateDataAll();

                }}

                PopulateData(); // Reload Table
                txt_cerca.setText("");
                combo_stato.setSelectedIndex(-1);
            }
            catch(SQLException | HeadlessException e)
            {
                JOptionPane.showMessageDialog(null,"Errore modifica stato");
            }
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void texTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texTagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texTagActionPerformed

    
    public void PopulateData() {
        this.tb1.setModel(new DefaultTableModel());
        this.txt_cerca.setText("");
        final DefaultTableModel model = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(final int column) {
                switch (column) {
                    case 0: {
                        return Boolean.class;
                    }
                    case 1: {
                        return String.class;
                    }
                    case 2: {
                        return String.class;
                    }
                    case 3: {
                        return String.class;
                    }
                    case 4: {
                        return String.class;
                    }
                    case 5: {
                        return String.class;
                    }
                    case 6: {
                        return String.class;
                    }
                    case 7: {
                        return String.class;
                    }
                    case 8: {
                        return String.class;
                    }
                    case 9: {
                        return String.class;
                    }
                    default: {
                        return String.class;
                    }
                }
            }
        };
        this.tb1.setModel(model);
        model.addColumn("");
        model.addColumn("Tag");
        model.addColumn("Cognome");
        model.addColumn("Nome");
        model.addColumn("Data di Nascita");
        model.addColumn("Recapito");
        model.addColumn("Stato");
        model.addColumn("");
        final String sql = "SELECT * FROM  pazienti ORDER BY cognome ASC";
        try {
            this.pstPop = this.conn.prepareStatement(sql);
            this.rsPop = this.pstPop.executeQuery();
            int row = 0;
            while (this.rsPop != null && this.rsPop.next()) {
                model.addRow(new Object[0]);
                model.setValueAt(false, row, 0);
                model.setValueAt(this.rsPop.getString("tag"), row, 1);
                model.setValueAt(this.rsPop.getString("cognome"), row, 2);
                model.setValueAt(this.rsPop.getString("nome"), row, 3);
                model.setValueAt(this.rsPop.getString("datanascita"), row, 4);
                model.setValueAt(this.rsPop.getString("cell"), row, 5);
                model.setValueAt(this.rsPop.getString("stato"), row, 6);
                model.setValueAt(this.rsPop.getString("id"), row, 7);
                ++row;
            }
            System.out.println("Numero righe tabella prestazioni: " + row);
            if (row == 0) {
                JOptionPane.showMessageDialog(null, "Nessun paziente disponibile");
            }
            this.tb1.getColumnModel().getColumn(0).setPreferredWidth(20);
            this.tb1.getColumnModel().getColumn(1).setPreferredWidth(60);
            this.tb1.getColumnModel().getColumn(2).setPreferredWidth(180);
            this.tb1.getColumnModel().getColumn(3).setPreferredWidth(180);
            this.tb1.getColumnModel().getColumn(4).setPreferredWidth(160);
            this.tb1.getColumnModel().getColumn(5).setPreferredWidth(160);
            this.tb1.getColumnModel().getColumn(6).setPreferredWidth(100);
            this.tb1.getColumnModel().getColumn(7).setMinWidth(0);
            this.tb1.getColumnModel().getColumn(7).setMaxWidth(0);
            this.tb1.getColumnModel().getColumn(7).setPreferredWidth(0);
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void Search() {
        this.tb1.setModel(new DefaultTableModel());
        final DefaultTableModel model = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(final int column) {
                switch (column) {
                    case 0: {
                        return Boolean.class;
                    }
                    case 1: {
                        return String.class;
                    }
                    case 2: {
                        return String.class;
                    }
                    case 3: {
                        return String.class;
                    }
                    case 4: {
                        return String.class;
                    }
                    case 5: {
                        return String.class;
                    }
                    case 6: {
                        return String.class;
                    }
                    case 7: {
                        return String.class;
                    }
                    case 8: {
                        return String.class;
                    }
                    case 9: {
                        return String.class;
                    }
                    default: {
                        return String.class;
                    }
                }
            }
        };
        this.tb1.setModel(model);
        model.addColumn("");
        model.addColumn("Tag");
        model.addColumn("Cognome");
        model.addColumn("Nome");
        model.addColumn("Data di Nascita");
        model.addColumn("Recapito");
        model.addColumn("Stato");
        model.addColumn("");
        final String cerca = this.txt_cerca.getText();
        if (cerca.equals("")) {
            this.PopulateData();
        }
        final String sql = "SELECT * FROM  pazienti WHERE nome LIKE ? or cognome LIKE ? or tag LIKE ? ORDER BY nome ASC";
        try {
            (this.pstSearch = this.connSearch.prepareStatement(sql)).setString(1, "%" + cerca + "%");
            this.pstSearch.setString(2, "%" + cerca + "%");
            this.pstSearch.setString(3, "%" + cerca + "%");
            this.rsSearch = this.pstSearch.executeQuery();
            int row = 0;
            while (this.rsSearch != null && this.rsSearch.next()) {
                model.addRow(new Object[0]);
                model.setValueAt(false, row, 0);
                model.setValueAt(this.rsSearch.getString("tag"), row, 1);
                model.setValueAt(this.rsSearch.getString("cognome"), row, 2);
                model.setValueAt(this.rsSearch.getString("nome"), row, 3);
                model.setValueAt(this.rsSearch.getString("datanascita"), row, 4);
                model.setValueAt(this.rsSearch.getString("cell"), row, 5);
                model.setValueAt(this.rsSearch.getString("stato"), row, 6);
                model.setValueAt(this.rsSearch.getString("id"), row, 7);
                ++row;
            }
            System.out.println("Numero righe tabella prestazioni: " + row);
            if (row == 0) {
                JOptionPane.showMessageDialog(null, "Nessun paziente disponibile");
                this.PopulateData();
            }
            this.tb1.getColumnModel().getColumn(0).setPreferredWidth(20);
            this.tb1.getColumnModel().getColumn(1).setPreferredWidth(60);
            this.tb1.getColumnModel().getColumn(2).setPreferredWidth(180);
            this.tb1.getColumnModel().getColumn(3).setPreferredWidth(180);
            this.tb1.getColumnModel().getColumn(4).setPreferredWidth(160);
            this.tb1.getColumnModel().getColumn(5).setPreferredWidth(160);
            this.tb1.getColumnModel().getColumn(6).setPreferredWidth(100);
            this.tb1.getColumnModel().getColumn(7).setMinWidth(0);
            this.tb1.getColumnModel().getColumn(7).setMaxWidth(0);
            this.tb1.getColumnModel().getColumn(7).setPreferredWidth(0);
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            this.PopulateData();
        }
    }
    
    void DeleteData(String strNome,String strCognome,String nascita,String id) {

        String sql = "DELETE FROM pazienti  WHERE nome = '" + strNome + "' AND cognome = '" + strCognome + "' and datanascita = '"+nascita+"' and id ='"+id+"'";
        try {
            pstDel = connDel.createStatement();
            System.out.println("QUERY DI ELIMINAZIONE: "+strNome+" "+strCognome+" "+nascita);
            pstDel.execute(sql);

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, e.getMessage());

        }

    }
    
     void DeleteDataRich(String cliente,String nascita) {

        String sql = "DELETE FROM richiami  WHERE cliente = '" + cliente + "' and datanascita = '"+nascita+"'";
        try {
            pstDel = connDel.createStatement();
            System.out.println("QUERY DI ELIMINAZIONE: "+cliente+" - "+nascita);
            pstDel.execute(sql);

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, e.getMessage());

        }

    }
    
    
    
    void DeleteDataPrest(String cliente,String id) {

        String sql = "DELETE FROM prestazione_cliente  WHERE cliente = '" + cliente + "' and cell = '"+id+"'";
        try {
            pstDelPrest = connDelPrest.createStatement();
            System.out.println("QUERY DI ELIMINAZIONE PRESTAZIONI: "+cliente+" "+id);
            pstDelPrest.execute(sql);
            //JOptionPane.showMessageDialog(null, "Prestazioni del paziente "+cliente+" eliminate correttamente");
        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, e.getMessage());

        }

                   
        

    }
    
//    void DeleteDataApp(String cliente) {
//
//        String sql = "DELETE FROM appuntamenti  WHERE cliente = '" + cliente + "'";
//        try {
//            pstDelApp = connDelApp.createStatement();
//            System.out.println("QUERY DI ELIMINAZIONE APPUNTAMENTI: "+cliente);
//            pstDelApp.execute(sql);
//            //JOptionPane.showMessageDialog(null, "Appuntamenti del paziente "+cliente+" eliminati correttamente");
//
//        } catch (SQLException e) {
//
//            JOptionPane.showMessageDialog(null, e.getMessage());
//
//        }
//
//                   
//        
//
//    }
    
    
    void DeleteDataCart(String cliente,String id) {

        String sql = "DELETE FROM cartella  WHERE paziente = '" + cliente + "' and cell = '"+id+"'";
        try {
            pstDelCli = connDelCli.createStatement();
            System.out.println("QUERY DI ELIMINAZIONE CARTELLA: "+cliente);
            pstDelCli.execute(sql);
            //JOptionPane.showMessageDialog(null, "Cartella clinica del paziente "+cliente+" eliminata correttamente");
            File file = new File("/dentalgest/cartelle/"+cliente+"-"+id);
            File file1 = new File("/dentalgest/reports/"+cliente+"-"+id);
            System.out.println("FIle 1: "+file1);
            deleteDirectory(file1);
            deleteDirectory(file);
            
            
            
        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, e.getMessage());

        } catch (IOException ex) {
            Logger.getLogger(ClientiList.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

void deleteDirectory(File file) throws IOException {
  if (file.isDirectory()) {
    File[] entries = file.listFiles();
    if (entries != null) {
      for (File entry : entries) {
        deleteDirectory(entry);
      }
    }
  }
  if (!file.delete()) {
    throw new IOException("Failed to delete " + file);
  }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientiList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ClientiList().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_agg_sek;
    private javax.swing.JButton bnt_mod;
    private javax.swing.JButton bt_cerca;
    private javax.swing.JButton bt_elim2;
    private javax.swing.JTextField cogn;
    private javax.swing.JComboBox<String> combo_stato;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooserBeanInfo jDateChooserBeanInfo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labTag;
    private javax.swing.JLabel lab_codfisc;
    private javax.swing.JLabel lab_formagiur;
    private javax.swing.JLabel lab_mail;
    private javax.swing.JLabel lab_pec;
    private javax.swing.JTextField nom;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField texTag;
    private javax.swing.JTextField txt_cerca;
    public javax.swing.JTextField txt_codfisc;
    private javax.swing.JTextField txt_cognome;
    public javax.swing.JTextField txt_nome;
    public javax.swing.JTextField txt_nominativo;
    public javax.swing.JTextField txt_recapito;
    private javax.swing.JTextField txtdataN;
    // End of variables declaration//GEN-END:variables
}
