/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DentalGest;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.UIManager;

/**
 *
 * @author Paolo
 */
public class Loading extends javax.swing.JFrame {
    
    
    
    
    /**
     * Creates new form Loading
     */
    public Loading() {
        super("Loading");
        initComponents();
                
		bar.setBounds(50,50, 250, 30);
		bar.setValue(0);
		bar.setStringPainted(true);
                bar.setBackground(Color.black);
                bar.setForeground(new Color(52,147,81));
                
        UIManager.put("bar.selectionBackground", Color.RED);
        UIManager.put("bar.selectionForeground", Color.WHITE);
                        
                        
		
         
        
    
    AnimationStation();
    }
    
    
    private void AnimationStation() {
    MouseAdapter ma = new MouseAdapter() {
        int lastX, lastY;
   
        @Override
        public void mousePressed(MouseEvent e) {
            lastX = e.getXOnScreen();
            lastY = e.getYOnScreen();
        }
        
        @Override
        public void mouseDragged(MouseEvent e) {
            int x = e.getXOnScreen();
            int y = e.getYOnScreen();
            // Move frame by the mouse delta
            setLocation(getLocationOnScreen().x + x - lastX,
                    getLocationOnScreen().y + y - lastY);
            lastX = x;
            lastY = y;
        }
    };
    addMouseListener(ma);
    addMouseMotionListener(ma);
}
    public void update()
	{
		int i=0;
		while( i<101)
		{
			bar.setValue(i);
			i++;
			
			try{
				Thread.sleep(100);
				
			}catch(InterruptedException e)
			{
			}
		}
                
                controlPanel l = new controlPanel();
                l.setVisible(true);
                
                
	}
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar.setBackground(new java.awt.Color(52, 147, 81));
        bar.setForeground(new java.awt.Color(0, 0, 0));
        bar.setAlignmentY(0.4F);
        bar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 147, 81), 2, true));
        bar.setStringPainted(true);
        getContentPane().add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 440, 40));

        setSize(new java.awt.Dimension(499, 490));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        
        Loading l = new Loading();
                        l.setVisible(true);
                        l.update();
                        l.dispose();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar;
    // End of variables declaration//GEN-END:variables
}
