/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DentalGest;

import java.awt.HeadlessException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Paolo
 */
public class modifica_adesione extends javax.swing.JFrame {
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    ResultSet rsc=null;
    /**
     * Creates new form adesione_servizi
     */
    private modifica_adesione() {
        initComponents();
        conn=Db.db();
         AnimationStation();
    }
    
    private static modifica_adesione obj=null;
    
    public static modifica_adesione getObj(){
        if(obj==null){
            obj=new modifica_adesione();
        }return obj;
    }
    
    
    private void AnimationStation() {
    MouseAdapter ma = new MouseAdapter() {
        int lastX, lastY;
   
        @Override
        public void mousePressed(MouseEvent e) {
            lastX = e.getXOnScreen();
            lastY = e.getYOnScreen();
        }
        
        @Override
        public void mouseDragged(MouseEvent e) {
            int x = e.getXOnScreen();
            int y = e.getYOnScreen();
            // Move frame by the mouse delta
            setLocation(getLocationOnScreen().x + x - lastX,
                    getLocationOnScreen().y + y - lastY);
            lastX = x;
            lastY = y;
        }
    };
    addMouseListener(ma);
    addMouseMotionListener(ma);
}
            
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_pec = new javax.swing.JTextField();
        txt_cell = new javax.swing.JTextField();
        lab_pec = new javax.swing.JLabel();
        lab_mail = new javax.swing.JLabel();
        lab_azienda = new javax.swing.JLabel();
        lab_codfisc = new javax.swing.JLabel();
        txt_fax = new javax.swing.JTextField();
        lab_cell = new javax.swing.JLabel();
        txt_tel = new javax.swing.JTextField();
        txt_via = new javax.swing.JTextField();
        txt_mail = new javax.swing.JTextField();
        lab_comune = new javax.swing.JLabel();
        lab_coadiuvanti = new javax.swing.JLabel();
        txt_partiva = new javax.swing.JTextField();
        txt_comune = new javax.swing.JTextField();
        lab_altrisoci = new javax.swing.JLabel();
        lab_fax = new javax.swing.JLabel();
        txt_azienda = new javax.swing.JTextField();
        txt_altrisoci = new javax.swing.JTextField();
        txt_formag = new javax.swing.JTextField();
        txt_codfisc = new javax.swing.JTextField();
        lab_via = new javax.swing.JLabel();
        txt_coadfam = new javax.swing.JTextField();
        lab_tel = new javax.swing.JLabel();
        lab_formagiur = new javax.swing.JLabel();
        lab_partiva = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bnt_del = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        combo_soc = new javax.swing.JComboBox();
        txt_cerca = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        combo_clienti = new javax.swing.JComboBox<>();
        bnt_del1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MascGest - Adesione ai servizi");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 147, 81));
        jLabel2.setText("Ricerca azienda:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 190, 150, 17);

        txt_pec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_pec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 147, 81)));
        getContentPane().add(txt_pec);
        txt_pec.setBounds(330, 430, 190, 19);

        txt_cell.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_cell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 147, 81)));
        getContentPane().add(txt_cell);
        txt_cell.setBounds(240, 350, 114, 19);

        lab_pec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_pec.setText("PEC:");
        getContentPane().add(lab_pec);
        lab_pec.setBounds(290, 430, 50, 17);

        lab_mail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_mail.setText("E-mail:");
        getContentPane().add(lab_mail);
        lab_mail.setBounds(20, 430, 41, 17);

        lab_azienda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_azienda.setText("Azienda / Persona fisica:");
        getContentPane().add(lab_azienda);
        lab_azienda.setBounds(30, 230, 150, 17);

        lab_codfisc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_codfisc.setText("Codice fiscale:");
        getContentPane().add(lab_codfisc);
        lab_codfisc.setBounds(20, 270, 85, 17);

        txt_fax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_fax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 147, 81)));
        txt_fax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_faxActionPerformed(evt);
            }
        });
        getContentPane().add(txt_fax);
        txt_fax.setBounds(390, 350, 130, 19);

        lab_cell.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_cell.setText("Cellulare:");
        getContentPane().add(lab_cell);
        lab_cell.setBounds(180, 350, 54, 17);

        txt_tel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_tel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 147, 81)));
        txt_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telActionPerformed(evt);
            }
        });
        getContentPane().add(txt_tel);
        txt_tel.setBounds(80, 350, 85, 19);

        txt_via.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_via.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 147, 81)));
        getContentPane().add(txt_via);
        txt_via.setBounds(320, 310, 200, 19);

        txt_mail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_mail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 147, 81)));
        getContentPane().add(txt_mail);
        txt_mail.setBounds(80, 430, 180, 19);

        lab_comune.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_comune.setText("Comune:");
        getContentPane().add(lab_comune);
        lab_comune.setBounds(20, 310, 57, 17);

        lab_coadiuvanti.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_coadiuvanti.setText("Coadiuvanti familiari:");
        getContentPane().add(lab_coadiuvanti);
        lab_coadiuvanti.setBounds(20, 510, 124, 17);

        txt_partiva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_partiva.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 147, 81)));
        getContentPane().add(txt_partiva);
        txt_partiva.setBounds(370, 270, 150, 19);

        txt_comune.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_comune.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 147, 81)));
        getContentPane().add(txt_comune);
        txt_comune.setBounds(80, 310, 205, 20);

        lab_altrisoci.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_altrisoci.setText("Altri soci:");
        getContentPane().add(lab_altrisoci);
        lab_altrisoci.setBounds(20, 470, 54, 17);

        lab_fax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_fax.setText("Fax:");
        getContentPane().add(lab_fax);
        lab_fax.setBounds(360, 350, 27, 17);

        txt_azienda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_azienda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 147, 81)));
        txt_azienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_aziendaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_azienda);
        txt_azienda.setBounds(180, 230, 340, 19);

        txt_altrisoci.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_altrisoci.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 147, 81)));
        getContentPane().add(txt_altrisoci);
        txt_altrisoci.setBounds(80, 470, 440, 19);

        txt_formag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_formag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 147, 81)));
        getContentPane().add(txt_formag);
        txt_formag.setBounds(120, 390, 400, 19);

        txt_codfisc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_codfisc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 147, 81)));
        getContentPane().add(txt_codfisc);
        txt_codfisc.setBounds(110, 270, 182, 19);

        lab_via.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_via.setText("Via:");
        getContentPane().add(lab_via);
        lab_via.setBounds(290, 310, 22, 17);

        txt_coadfam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_coadfam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 147, 81)));
        getContentPane().add(txt_coadfam);
        txt_coadfam.setBounds(160, 510, 360, 19);

        lab_tel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_tel.setText("Telefono:");
        getContentPane().add(lab_tel);
        lab_tel.setBounds(20, 350, 57, 17);

        lab_formagiur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_formagiur.setText("Forma giuridica:");
        getContentPane().add(lab_formagiur);
        lab_formagiur.setBounds(20, 390, 97, 17);

        lab_partiva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab_partiva.setText("Partita Iva:");
        getContentPane().add(lab_partiva);
        lab_partiva.setBounds(300, 270, 67, 17);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DentalGest/images/chiudi.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(515, 10, 20, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DentalGest/images/minimizza.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(496, 10, 20, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Affida alla Confagricoltura di AVELLINO ovvero alla Società di Servizi denominata SE'KOMA SERVIZI SRL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 550, 522, 13);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setText("ciascuna per le proprie competenze, l'espletamento dei servizi e attività:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 570, 340, 13);

        bnt_del.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bnt_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DentalGest/images/elimina.png"))); // NOI18N
        bnt_del.setAlignmentX(0.5F);
        bnt_del.setBorder(null);
        bnt_del.setBorderPainted(false);
        bnt_del.setContentAreaFilled(false);
        bnt_del.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bnt_del.setRolloverEnabled(false);
        bnt_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_delActionPerformed(evt);
            }
        });
        getContentPane().add(bnt_del);
        bnt_del.setBounds(430, 110, 70, 25);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DentalGest/images/modifica.png"))); // NOI18N
        jButton2.setAlignmentX(0.5F);
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setRolloverEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 80, 70, 25);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DentalGest/images/aggiungi.png"))); // NOI18N
        jButton1.setAlignmentX(0.5F);
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 80, 70, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Società:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 80, 50, 17);

        combo_soc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_soc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Confagricoltura Avellino", "Se Koma Servizi SRL" }));
        combo_soc.setSelectedIndex(-1);
        combo_soc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 147, 81)));
        getContentPane().add(combo_soc);
        combo_soc.setBounds(80, 80, 180, 20);

        txt_cerca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_cerca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 147, 81)));
        txt_cerca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cercaKeyReleased(evt);
            }
        });
        getContentPane().add(txt_cerca);
        txt_cerca.setBounds(180, 190, 300, 19);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Azienda:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 110, 60, 17);

        combo_clienti.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_clienti.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combo_clientiPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                combo_clientiPopupMenuWillBecomeVisible(evt);
            }
        });
        getContentPane().add(combo_clienti);
        combo_clienti.setBounds(90, 110, 320, 22);

        bnt_del1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bnt_del1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DentalGest/images/cancella.png"))); // NOI18N
        bnt_del1.setAlignmentX(0.5F);
        bnt_del1.setBorder(null);
        bnt_del1.setBorderPainted(false);
        bnt_del1.setContentAreaFilled(false);
        bnt_del1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bnt_del1.setRolloverEnabled(false);
        bnt_del1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_del1ActionPerformed(evt);
            }
        });
        getContentPane().add(bnt_del1);
        bnt_del1.setBounds(430, 80, 70, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DentalGest/images/gestione-clienti.png"))); // NOI18N
        jLabel6.setAlignmentX(0.5F);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 540, 630);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DentalGest/images/minimizza.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(960, 20, 20, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DentalGest/images/chiudi.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(980, 20, 20, 20);

        setSize(new java.awt.Dimension(539, 627));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_aziendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_aziendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_aziendaActionPerformed

    private void txt_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telActionPerformed

    private void txt_faxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_faxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_faxActionPerformed

    private void bnt_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_delActionPerformed
        // TODO add your handling code here:
        
        int x = JOptionPane.showConfirmDialog(null,"Sei sicuro di voler eliminare la seguente adesione?","Elimina Adesione",JOptionPane.YES_NO_OPTION);
        if(x==0){
            try{
                String tmp = txt_cerca.getText();
                String soc = combo_soc.getSelectedItem().toString();
                String sql = "delete from adesione where azienda='"+tmp+"' and soc='"+soc+"'";
                pst=conn.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null,"Adesione cancellata correttamente");
                
                txt_cerca.setText("");
                txt_azienda.setText("");
                txt_codfisc.setText("");
                txt_partiva.setText("");
                txt_comune.setText("");
                txt_via.setText("");
                txt_tel.setText("");
                txt_cell.setText("");
                txt_fax.setText("");
                txt_mail.setText("");
                txt_pec.setText("");
                txt_formag.setText("");
                txt_altrisoci.setText("");
                txt_coadfam.setText("");
                combo_soc.setSelectedItem("- Seleziona Societa' -");
            }
            catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, e);
            }
            finally{
                try{
                    rs.close();
                    pst.close();
                }
                catch(SQLException e){
                }

            }
        }
        
    }//GEN-LAST:event_bnt_delActionPerformed

    private void txt_cercaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cercaKeyReleased
        // TODO add your handling code here:
       
        try{
            
            String cerca= txt_cerca.getText().toLowerCase();
            
           txt_azienda.setText("");
           txt_codfisc.setText("");
           txt_partiva.setText("");
           txt_comune.setText("");
           txt_via.setText("");
           txt_tel.setText("");
           txt_cell.setText("");
           txt_fax.setText("");
           txt_mail.setText("");
           txt_pec.setText("");
           txt_formag.setText("");
           txt_altrisoci.setText("");
           txt_coadfam.setText("");
           combo_soc.setSelectedItem("- Seleziona Societa'-");
           
                
            
        String sql = "select * from adesione where azienda like '"+cerca+"'";
        
        Statement pst=conn.createStatement();
        rs=pst.executeQuery(sql);
        while(rs.next()){
             
             txt_azienda.setText(rs.getString("azienda"));
             txt_codfisc.setText(rs.getString("codfisc"));
             txt_partiva.setText(rs.getString("partiva"));
             txt_comune.setText(rs.getString("comune"));
             txt_via.setText(rs.getString("via"));
             txt_tel.setText(rs.getString("tel"));
             txt_cell.setText(rs.getString("cell"));
             txt_fax.setText(rs.getString("fax"));
             txt_mail.setText(rs.getString("mail"));
             txt_pec.setText(rs.getString("pec"));
             txt_formag.setText(rs.getString("forma"));
             txt_altrisoci.setText(rs.getString("altri"));
             txt_coadfam.setText(rs.getString("coadiufam"));
             combo_soc.setSelectedItem(rs.getString("soc"));

             
        }
        }catch(SQLException e){
            
        }
    }//GEN-LAST:event_txt_cercaKeyReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:

       dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        setExtendedState(JFrame.ICONIFIED );
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null,"Sei sicuro di voler aggiugere la seguente adesione?","Aggiungi Adesione",JOptionPane.YES_NO_OPTION);
        if(x==0){
        try{
            
            String sql="insert into adesione (azienda,codfisc,partiva,comune,via,tel,cell,fax,mail,pec,forma,altri,coadiufam,soc) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)" ; 
            pst=conn.prepareStatement(sql);            
            
            pst.setString(1,txt_azienda.getText().toLowerCase());
            pst.setString(2,txt_codfisc.getText().toLowerCase());
            pst.setString(3,txt_partiva.getText().toLowerCase());
            pst.setString(4,txt_comune.getText().toLowerCase());
            pst.setString(5,txt_via.getText().toLowerCase());
            pst.setString(6,txt_tel.getText().toLowerCase());
            pst.setString(7,txt_cell.getText().toLowerCase());
            pst.setString(8,txt_fax.getText().toLowerCase());
            pst.setString(9,txt_mail.getText().toLowerCase());
            pst.setString(10,txt_pec.getText().toLowerCase());
            pst.setString(11,txt_formag.getText().toLowerCase());
            pst.setString(12,txt_altrisoci.getText().toLowerCase());
            pst.setString(13,txt_coadfam.getText().toLowerCase());
            pst.setString(14,combo_soc.getSelectedItem().toString());
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"Adesione aggiunta correttamente" );
           txt_cerca.setText("");
            
           txt_azienda.setText("");
           txt_codfisc.setText("");
           txt_partiva.setText("");
           txt_comune.setText("");
           txt_via.setText("");
           txt_tel.setText("");
           txt_cell.setText("");
           txt_fax.setText("");
           txt_mail.setText("");
           txt_pec.setText("");
           txt_formag.setText("");
           txt_altrisoci.setText("");
           txt_coadfam.setText("");
           combo_soc.setSelectedItem("- Seleziona Societa' -"); 
        
        }
    catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null,"Errore aggiunta adesione");
      }
       
        finally{
            try{
                rs.close();
                pst.close();
            }
            catch(SQLException e)
        {
            
      }
        } } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null,"Sei sicuro di voler aggiornare la seguente adesione?","Aggiorna Adesione",JOptionPane.YES_NO_OPTION);
        if(x==0){
        try{
            
          
           String val4 = txt_azienda.getText().toLowerCase();
           String val5 = txt_codfisc.getText().toLowerCase();
           String val6 = txt_partiva.getText().toLowerCase();
           String val7 = txt_comune.getText().toLowerCase();
           String val8 = txt_via.getText().toLowerCase();
           String val9 = txt_tel.getText().toLowerCase();
           String val10 = txt_cell.getText().toLowerCase();
           String val11 = txt_fax.getText().toLowerCase();
           String val12 = txt_mail.getText().toLowerCase();
           String val13 = txt_pec.getText().toLowerCase();
           String val14 = txt_formag.getText().toLowerCase();
           String val15 = txt_altrisoci.getText().toLowerCase();
           String val16 = txt_coadfam.getText().toLowerCase();
           String soc=combo_soc.getSelectedItem().toString();
            
            String sql="update adesione set azienda='"+val4+"',codfisc='"+val5+"',partiva='"+val6+"',comune='"+val7+"',via='"+val8+"',tel='"+val9+"',cell='"+val10+"',fax='"+val11+"',mail='"+val12+"',pec='"+val13+"',forma='"+val14+"',altri='"+val15+"',coadiufam='"+val16+"',soc='"+soc+"' where azienda='"+val4+"'"; 
            pst=conn.prepareStatement(sql);            
            pst.execute();
            JOptionPane.showMessageDialog(null,"Adesione modificata correttamente" );
           txt_cerca.setText("");
           combo_soc.setSelectedItem("");
           
           txt_azienda.setText("");
           txt_codfisc.setText("");
           txt_partiva.setText("");
           txt_comune.setText("");
           txt_via.setText("");
           txt_tel.setText("");
           txt_cell.setText("");
           txt_fax.setText("");
           txt_mail.setText("");
           txt_pec.setText("");
           txt_formag.setText("");
           txt_altrisoci.setText("");
           txt_coadfam.setText("");
           combo_soc.setSelectedItem("- Seleziona Societa' -");
        }
    catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null,"Errore modifica adesione");
      }
       
        finally{
            try{
                rs.close();
                pst.close();
            }
            catch(SQLException e)
        {
            
      }
        } }    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        setExtendedState(JFrame.ICONIFIED );
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void combo_clientiPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combo_clientiPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        combo_clienti.removeAllItems();
        try{   
            String tipo= combo_soc.getSelectedItem().toString();
            
           txt_azienda.setText("");
           txt_codfisc.setText("");
           txt_partiva.setText("");
           txt_comune.setText("");
           txt_via.setText("");
           txt_tel.setText("");
           txt_cell.setText("");
           txt_fax.setText("");
           txt_mail.setText("");
           txt_pec.setText("");
           txt_formag.setText("");
           txt_altrisoci.setText("");
           txt_coadfam.setText("");
           combo_soc.setSelectedItem("- Seleziona Societa'-");
           
                
            
        String sql = "select azienda from adesione where soc = '"+tipo+"' ORDER BY azienda  ASC";
        
        Statement pst=conn.createStatement();
        rs=pst.executeQuery(sql);
        while(rs.next()){
            combo_clienti.addItem(rs.getString("azienda"));
             
             
        }
        }catch(SQLException e){

        
        }
        
        
    }//GEN-LAST:event_combo_clientiPopupMenuWillBecomeVisible

    private void combo_clientiPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combo_clientiPopupMenuWillBecomeInvisible
        // TODO add your handling code here:try{
        
        try{
            
            String nome= combo_clienti.getSelectedItem().toString();
            
           txt_cerca.setText(nome);
           txt_azienda.setText("");
           txt_codfisc.setText("");
           txt_partiva.setText("");
           txt_comune.setText("");
           txt_via.setText("");
           txt_tel.setText("");
           txt_cell.setText("");
           txt_fax.setText("");
           txt_mail.setText("");
           txt_pec.setText("");
           txt_formag.setText("");
           txt_altrisoci.setText("");
           txt_coadfam.setText("");
           combo_soc.setSelectedItem("- Seleziona Societa'-");
           
                
            
        String sql = "select * from adesione where azienda = '"+nome+"'";
        
        Statement pst=conn.createStatement();
        rs=pst.executeQuery(sql);
        while(rs.next()){
             
             txt_azienda.setText(rs.getString("azienda"));
             txt_codfisc.setText(rs.getString("codfisc"));
             txt_partiva.setText(rs.getString("partiva"));
             txt_comune.setText(rs.getString("comune"));
             txt_via.setText(rs.getString("via"));
             txt_tel.setText(rs.getString("tel"));
             txt_cell.setText(rs.getString("cell"));
             txt_fax.setText(rs.getString("fax"));
             txt_mail.setText(rs.getString("mail"));
             txt_pec.setText(rs.getString("pec"));
             txt_formag.setText(rs.getString("forma"));
             txt_altrisoci.setText(rs.getString("altri"));
             txt_coadfam.setText(rs.getString("coadiufam"));
             combo_soc.setSelectedItem(rs.getString("soc"));

             
        }
        }catch(SQLException e){
            
        }
    }//GEN-LAST:event_combo_clientiPopupMenuWillBecomeInvisible

    private void bnt_del1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_del1ActionPerformed
        // TODO add your handling code here:
        combo_clienti.removeAllItems();
        combo_soc.setSelectedItem("");
        txt_azienda.setText("");
           txt_codfisc.setText("");
           txt_partiva.setText("");
           txt_comune.setText("");
           txt_via.setText("");
           txt_tel.setText("");
           txt_cell.setText("");
           txt_fax.setText("");
           txt_mail.setText("");
           txt_pec.setText("");
           txt_formag.setText("");
           txt_altrisoci.setText("");
           txt_coadfam.setText("");
           combo_soc.setSelectedItem("- Seleziona Societa'-");
    }//GEN-LAST:event_bnt_del1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modifica_adesione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modifica_adesione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modifica_adesione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modifica_adesione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new modifica_adesione().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_del;
    private javax.swing.JButton bnt_del1;
    private javax.swing.JComboBox<String> combo_clienti;
    private javax.swing.JComboBox combo_soc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lab_altrisoci;
    private javax.swing.JLabel lab_azienda;
    private javax.swing.JLabel lab_cell;
    private javax.swing.JLabel lab_coadiuvanti;
    private javax.swing.JLabel lab_codfisc;
    private javax.swing.JLabel lab_comune;
    private javax.swing.JLabel lab_fax;
    private javax.swing.JLabel lab_formagiur;
    private javax.swing.JLabel lab_mail;
    private javax.swing.JLabel lab_partiva;
    private javax.swing.JLabel lab_pec;
    private javax.swing.JLabel lab_tel;
    private javax.swing.JLabel lab_via;
    private javax.swing.JTextField txt_altrisoci;
    private javax.swing.JTextField txt_azienda;
    private javax.swing.JTextField txt_cell;
    private javax.swing.JTextField txt_cerca;
    private javax.swing.JTextField txt_coadfam;
    private javax.swing.JTextField txt_codfisc;
    private javax.swing.JTextField txt_comune;
    private javax.swing.JTextField txt_fax;
    private javax.swing.JTextField txt_formag;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_partiva;
    private javax.swing.JTextField txt_pec;
    private javax.swing.JTextField txt_tel;
    private javax.swing.JTextField txt_via;
    // End of variables declaration//GEN-END:variables
}
