/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DentalGest;

import com.itextpdf.text.Element;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Font;
import com.lowagie.text.Image;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Paolo
 */
public class report extends javax.swing.JFrame {

    /**
     * Creates new form report
     */
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    public report() {
        initComponents();
        conn=Db.db();
        AnimationStation();
    }

    private void AnimationStation() {
    MouseAdapter ma = new MouseAdapter() {
        int lastX, lastY;
   
        @Override
        public void mousePressed(MouseEvent e) {
            lastX = e.getXOnScreen();
            lastY = e.getYOnScreen();
        }
        
        @Override
        public void mouseDragged(MouseEvent e) {
            int x = e.getXOnScreen();
            int y = e.getYOnScreen();
            // Move frame by the mouse delta
            setLocation(getLocationOnScreen().x + x - lastX,
                    getLocationOnScreen().y + y - lastY);
            lastX = x;
            lastY = y;
        }
    };
    addMouseListener(ma);
    addMouseMotionListener(ma);
}
    private static report obj=null;
    
    public static report getObj(){
        if(obj==null){
            obj=new report();
        }return obj;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comb_soc = new javax.swing.JComboBox<>();
        bnt_agg_sek = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setFocusableWindowState(false);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DentalGest/images/chiudi.png"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setAlignmentY(1.0F);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 6, 20, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DentalGest/images/minimizza.png"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 6, 20, 20));

        comb_soc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comb_soc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Confagricoltura Avellino", "Se Koma Servizi SRL" }));
        comb_soc.setSelectedIndex(-1);
        comb_soc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 147, 81)));
        getContentPane().add(comb_soc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 210, 25));

        bnt_agg_sek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DentalGest/images/genera.png"))); // NOI18N
        bnt_agg_sek.setBorder(null);
        bnt_agg_sek.setBorderPainted(false);
        bnt_agg_sek.setContentAreaFilled(false);
        bnt_agg_sek.setFocusPainted(false);
        bnt_agg_sek.setFocusable(false);
        bnt_agg_sek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_agg_sekActionPerformed(evt);
            }
        });
        getContentPane().add(bnt_agg_sek, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 147, 81));
        jLabel2.setText("Seleziona Società:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DentalGest/images/Senza-titolo-.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 270));

        setSize(new java.awt.Dimension(488, 268));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bnt_agg_sekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_agg_sekActionPerformed
        // TODO add your handling code here:
        try{
            String soc = comb_soc.getSelectedItem().toString();
            if(soc.isEmpty()){JOptionPane.showMessageDialog(null, "Selezionare una società dal menu a tendina");}
            else{
                int x = JOptionPane.showConfirmDialog(null,"Sei sicuro di voler generare il seguente report?","Genera Report",JOptionPane.YES_NO_OPTION);
                if(x==0){
                String sql = "select * from adesione where soc='"+soc+"'";
        Document d=new Document();
            PdfWriter.getInstance(d, new FileOutputStream("c:/mascgest/reports/ElencoAdesioni-"+soc+".pdf"));
            d.open();
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            Image image = Image.getInstance("c:/mascgest/testata.png");
            PdfPCell cell=new PdfPCell();
            d.add(image);
            Paragraph n=new Paragraph("\n");
            cell.setColspan(2);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setPadding(8.0f);
            Font font=new Font();
            font.setColor(52,147,81);
            font.setSize(28);
            d.add(n);d.add(n);
            
            d.add(n);
            
            while(rs.next()){
               PdfPTable ptable = new PdfPTable(2);
               String azienda=rs.getString("azienda");
               String pa=rs.getString("partiva");
               String cf=rs.getString("codfisc");
               String comu=rs.getString("comune");
               String via=rs.getString("via");
               String cellu=rs.getString("cell");
               String tel=rs.getString("tel");
               String mail=rs.getString("mail");
               String pec=rs.getString("pec");
               PdfPCell cell1=new PdfPCell(new Paragraph(azienda+"\n"));
               cell1.setBorder(1);
               font.setColor(Color.black);
               cell1.setHorizontalAlignment(Element.ALIGN_LEFT);
               PdfPCell cell2=new PdfPCell(new Paragraph("P.Iva:"+pa+" - C.F:"+cf+"\nComune:"+comu+" - Via:"+via+"\nCell:"+cellu+" - Tel:"+tel+"\nMail:"+mail+" - Pec:"+pec+"\n\n"));
                cell2.setBorder(1);
                cell2.setHorizontalAlignment(Element.ALIGN_LEFT);
                ptable.addCell(cell1);
                ptable.addCell(cell2);
                d.add(ptable);
                 d.add(n);
                d.add(n);
            }
               
            
            d.close();
            
            JOptionPane.showMessageDialog(null,"Report creato correttamente");
         try{
        Process exec = Runtime.getRuntime().exec("cmd.exe /C c:/mascgest/utility/open.exe");       }
         catch (IOException e){}}}}
        catch(HeadlessException e){
            JOptionPane.showMessageDialog(null,"Errore creazione report");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Clients.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException | SQLException | IOException ex) {
            Logger.getLogger(Clients.class.getName()).log(Level.SEVERE, null, ex);
        } 
        finally {

            try{

                rs.close();
                pst.close();
                

            }
            catch(SQLException e){

            }
        
        }
    }//GEN-LAST:event_bnt_agg_sekActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
         this.dispose();
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        setExtendedState( JFrame.ICONIFIED );
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_agg_sek;
    private javax.swing.JComboBox<String> comb_soc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
